spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  datasource:
    url: jdbc:oracle:thin:@192.168.1.112:1521:xe
    username: hanshuo2
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    # 关闭mybatis-plus的banner打印
    global-config:
      banner: false
#  logging:
#    config: classpath:logback-dev.xml

  output:
    ansi:
      enabled: always
server:
  port: 9999




